WIDTH = 800
HEIGHT = 480
HALF_WINDOW_W = WIDTH / 2
HALF_WINDOW_H = HEIGHT / 2

# Size of level, including both the pitch and the boundary surrounding it
LEVEL_W = 1000
LEVEL_H = 1400
HALF_LEVEL_W = LEVEL_W // 2
HALF_LEVEL_H = LEVEL_H // 2

PLAYER_W = 20
PLAYER_H = 25

# Animation
MAX_ANIMATION_FRAMES = 4
FRAME_TIME = 20
HURT_DURATION = 2
HURT_COOLDOWN = 10

# Spawning
SPAWN_RATE = 20 
SPAWN_DISTANCE = 50